### ISSUE TITLE
Blog page default is a bit confusing

### ISSUE THREAD

**Issue by johnstonphilip** [brandid/hello-pro#6]
**Describe the bug**
When I go to edit my blog page, I see a paragraph block that says `This is where the magic happens! Include a brief paragraph at the top of your blog so readers know what topics or themes they can expect to read about — and look forward to! ok.`

On the frontend, it is loading the archive-portfolio.php template, and the contents of that block are not used. Could that paragraph be removed, or help make it clear that the page's content does not come from Gutenberg?

<img width="877" alt="Screen Shot 2020-03-06 at 3 24 02 PM" src="https://user-images.githubusercontent.com/7538525/76120068-b9920180-5fbe-11ea-83f1-3a596c19983f.png">

**Comment by alexmustin** [comment]
This paragraph of text is indeed part of the Block Editor page content, on the page called 'Blog'. During One-Click Theme Setup, the 'Blog' page is created, then this content is added, then the page is assigned to be the Blog Archive page in Settings > Reading.

I do notice, however, a weird issue now where this block content is not displaying (but it used to in previous versions of Genesis).

I removed the files 'archive-portfolio.php' and 'single-portfolio.php' and the issue persists -- I still do not see the blocks I've created showing up on the front-end when the page is assigned to be the Blog Archive page in Settings > Reading.

I tested this by adding the following code to functions.php -- this will output which page template is currently being used on each page:
```
add_action('wp_head', 'show_template');
function show_template() {
	global $template;
	global $current_user;
	wp_get_current_user();
	if ($current_user->user_level == 10 ) print_r($template);
}
```

When I add this and navigate to the Blog page, it shows I'm using the template:
**.../wp-content/themes/genesis/index.php**

I notice when I test out this same Blog page using the 'Genesis Sample' theme, the paragraph blocks I added onto the page still do not display when viewing the Blog Archive page:
[https://i.imgur.com/ZPirtUu.jpg](https://i.imgur.com/ZPirtUu.jpg)
[https://i.imgur.com/rgSMA1v.jpg](https://i.imgur.com/rgSMA1v.jpg)

If I change the Settings > Reading option so the Blog page is no longer assigned to be the Archive page, my paragraph blocks suddenly appear.

Since this content never displays on the Genesis Blog Archive, I will remove it from the One-Click Theme Setup import. We will also make appropriate edits to our Theme Documentation so this text is removed from any screenshots or instructions.

Thanks!
